name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore src/EventMemoria.Web/EventMemoria.Web.csproj

    - name: Build application
      run: dotnet build src/EventMemoria.Web/EventMemoria.Web.csproj --configuration Release --no-restore
