name: Build and Test

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: ⚙️ Setup Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.15.0
        cache: 'npm'
        cache-dependency-path: src/EventMemoria.Web/client/bun.lock

    - name: 📦 Install dependencies
      run: npm install -g bun && cd src/EventMemoria.Web/client && bun install

    - name: 🛠️ Build the project
      run: cd src/EventMemoria.Web/client && npm run build:prod
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore src/EventMemoria.Web/EventMemoria.Web.csproj

    - name: Build application
      run: dotnet build src/EventMemoria.Web/EventMemoria.Web.csproj --configuration Release --no-restore

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./src/EventMemoria.Web
        file: ./src/EventMemoria.Web/Dockerfile
        push: false
        tags: eventmemoria:latest
