name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore Vogelhochzeit/Vogelhochzeit.csproj
    
    - name: Build application
      run: dotnet build Vogelhochzeit/Vogelhochzeit.csproj --configuration Release --no-restore
    
    - name: Run tests
      run: dotnet test Vogelhochzeit/Vogelhochzeit.csproj --configuration Release --no-build --logger trx
      continue-on-error: true
    
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: .NET Tests
        path: '**/*.trx'
        reporter: dotnet-trx
        fail-on-error: false
